; PlatformIO Configuration for Profiling Float New
; https://docs.platformio.org/page/projectconf.html

[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags = -I include
lib_deps =
    bluerobotics/BlueRobotics MS5837 Library@^1.1.1
board_build.partitions = min_spiffs.csv

; OTA upload (uncomment and set IP to flash over WiFi)
; upload_protocol = espota
; upload_port = 192.168.4.1

[env:test_manual_stepper]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = -<main.cpp> +<../test/manual_stepper/main.cpp>

[env:test_pressure]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    bluerobotics/BlueRobotics MS5837 Library@^1.1.1
build_src_filter = -<main.cpp> +<../test/pressure_only/main.cpp>

[env:test_buttons]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = -<main.cpp> +<../test/button_test/main.cpp>

[env:wokwi_stepper_debug]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags = -I include
build_src_filter = -<main.cpp> +<../test/wokwi_stepper_debug/main.cpp>

[env:wokwi_stepper_auto]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags = -I include
build_src_filter = -<main.cpp> +<../test/wokwi_stepper_auto/main.cpp>
